# Generated by Django 5.2.7 on 2026-05-01 13:00

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('students', '0002_studentcorrectionrequest'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AnalyticsETLRun',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('status', models.CharField(choices=[('STARTED', 'Started'), ('SUCCEEDED', 'Succeeded'), ('FAILED', 'Failed'), ('PARTIAL', 'Partial')], default='STARTED', max_length=16)),
                ('started_at', models.DateTimeField(auto_now_add=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('students_processed', models.PositiveIntegerField(default=0)),
                ('snapshots_created', models.PositiveIntegerField(default=0)),
                ('snapshots_updated', models.PositiveIntegerField(default=0)),
                ('moodle_snapshots_used', models.PositiveIntegerField(default=0)),
                ('failure_count', models.PositiveIntegerField(default=0)),
                ('last_error', models.TextField(blank=True)),
                ('dry_run', models.BooleanField(default=False)),
                ('metadata', models.JSONField(blank=True, default=dict)),
            ],
            options={
                'ordering': ['-started_at', 'id'],
            },
        ),
        migrations.CreateModel(
            name='StudentAnalyticsSnapshot',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('academic_year', models.CharField(max_length=32)),
                ('semester', models.CharField(max_length=64)),
                ('programme', models.CharField(max_length=128)),
                ('year_of_study', models.PositiveSmallIntegerField()),
                ('academic_standing', models.CharField(max_length=32)),
                ('attendance_average', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('financial_flag_count', models.PositiveIntegerField(default=0)),
                ('active_enrollment_count', models.PositiveIntegerField(default=0)),
                ('draft_grade_count', models.PositiveIntegerField(default=0)),
                ('official_grade_count', models.PositiveIntegerField(default=0)),
                ('gpa', models.DecimalField(blank=True, decimal_places=2, max_digits=4, null=True)),
                ('latest_moodle_access_at', models.DateTimeField(blank=True, null=True)),
                ('latest_moodle_course_access_at', models.DateTimeField(blank=True, null=True)),
                ('moodle_snapshot_count', models.PositiveIntegerField(default=0)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('source_run', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='snapshots', to='analytics.analyticsetlrun')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='analytics_snapshots', to='students.studentprofile')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='student_analytics_snapshots', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['student__student_number', 'academic_year', 'semester'],
                'indexes': [models.Index(fields=['academic_year', 'semester'], name='analytics_snapshot_term_idx'), models.Index(fields=['programme'], name='analytics_snap_prog_idx'), models.Index(fields=['updated_at'], name='analytics_snapshot_updated_idx')],
                'constraints': [models.UniqueConstraint(fields=('student', 'academic_year', 'semester'), name='analytics_unique_student_snapshot_per_term')],
            },
        ),
    ]
