# Generated by Django 6.0.5 on 2026-05-10 16:50

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("students", "0002_studentcorrectionrequest"),
    ]

    operations = [
        migrations.CreateModel(
            name="WellbeingAuditLog",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("checkin_id", models.UUIDField(blank=True, null=True)),
                (
                    "triage_class",
                    models.CharField(
                        choices=[
                            ("NORMAL", "Normal"),
                            ("CONCERNING", "Concerning"),
                            ("ESCALATE", "Escalate"),
                        ],
                        max_length=12,
                    ),
                ),
                ("notification_sent", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "student",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="wellbeing_audit_logs",
                        to="students.studentprofile",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="WellbeingConsent",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("is_enabled", models.BooleanField(default=False)),
                ("consented_at", models.DateTimeField(blank=True, null=True)),
                ("revoked_at", models.DateTimeField(blank=True, null=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "student",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="wellbeing_consent",
                        to="students.studentprofile",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="WellbeingCheckIn",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("mood_rating", models.PositiveSmallIntegerField()),
                ("comment", models.TextField(blank=True)),
                (
                    "triage_class",
                    models.CharField(
                        choices=[
                            ("NORMAL", "Normal"),
                            ("CONCERNING", "Concerning"),
                            ("ESCALATE", "Escalate"),
                        ],
                        default="NORMAL",
                        max_length=12,
                    ),
                ),
                ("is_deleted_by_student", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "student",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="wellbeing_checkins",
                        to="students.studentprofile",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["student", "-created_at"], name="wb_student_idx"
                    ),
                    models.Index(
                        fields=["triage_class", "-created_at"], name="wb_triage_idx"
                    ),
                ],
            },
        ),
    ]
