# Generated by Django 5.2.7 on 2026-04-30 16:20

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('category', models.CharField(choices=[('ACADEMIC', 'Academic'), ('MOODLE', 'Moodle'), ('GRADES', 'Grades'), ('ENROLLMENT', 'Enrollment'), ('ADVISING', 'Advising'), ('SYSTEM', 'System')], max_length=16)),
                ('severity', models.CharField(choices=[('INFO', 'Info'), ('SUCCESS', 'Success'), ('WARNING', 'Warning'), ('ERROR', 'Error')], max_length=16)),
                ('title', models.CharField(max_length=160)),
                ('message', models.TextField()),
                ('action_label', models.CharField(blank=True, max_length=80)),
                ('action_url', models.CharField(blank=True, max_length=255)),
                ('is_read', models.BooleanField(default=False)),
                ('read_at', models.DateTimeField(blank=True, null=True)),
                ('source_type', models.CharField(blank=True, max_length=128)),
                ('source_id', models.CharField(blank=True, max_length=128)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('recipient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at', '-id'],
                'indexes': [models.Index(fields=['recipient', 'is_read', '-created_at'], name='notif_rec_read_idx'), models.Index(fields=['recipient', 'category', '-created_at'], name='notifications_category_idx'), models.Index(fields=['recipient', 'severity', '-created_at'], name='notifications_severity_idx'), models.Index(fields=['source_type', 'source_id'], name='notifications_source_idx')],
            },
        ),
    ]
