# Generated by Django 5.2 on 2026-04-30

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("accounts", "0003_user_full_name_user_must_reset_password_accesslog"),
    ]

    operations = [
        migrations.CreateModel(
            name="AuditEvent",
            fields=[
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ("actor_username", models.CharField(blank=True, max_length=150)),
                ("actor_role", models.CharField(blank=True, max_length=32)),
                (
                    "category",
                    models.CharField(
                        choices=[
                            ("USER", "User"),
                            ("STUDENT_RECORD", "Student Record"),
                            ("COURSE", "Course"),
                            ("ENROLLMENT", "Enrollment"),
                            ("GRADE", "Grade"),
                            ("MOODLE", "Moodle"),
                            ("NOTIFICATION", "Notification"),
                            ("LTI", "LTI"),
                            ("SYSTEM", "System"),
                        ],
                        db_index=True,
                        max_length=32,
                    ),
                ),
                ("action", models.CharField(db_index=True, max_length=80)),
                ("summary", models.TextField()),
                ("target_type", models.CharField(blank=True, max_length=128)),
                ("target_id", models.CharField(blank=True, max_length=128)),
                (
                    "severity",
                    models.CharField(
                        choices=[("INFO", "Info"), ("SUCCESS", "Success"), ("WARNING", "Warning"), ("ERROR", "Error")],
                        db_index=True,
                        default="INFO",
                        max_length=16,
                    ),
                ),
                ("metadata", models.JSONField(blank=True, default=dict)),
                ("ip_address", models.GenericIPAddressField(blank=True, null=True)),
                ("user_agent", models.CharField(blank=True, max_length=255)),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                (
                    "actor",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="audit_events",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at", "-id"],
                "indexes": [
                    models.Index(fields=["created_at"], name="audit_created_idx"),
                    models.Index(fields=["category", "created_at"], name="audit_cat_created_idx"),
                    models.Index(fields=["severity", "created_at"], name="audit_sev_created_idx"),
                    models.Index(fields=["action", "created_at"], name="audit_action_created_idx"),
                    models.Index(fields=["actor", "created_at"], name="audit_actor_created_idx"),
                    models.Index(fields=["target_type", "target_id"], name="audit_target_idx"),
                ],
            },
        ),
    ]
