# Generated by Django 5.2.7 on 2026-04-30 21:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('audit', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auditevent',
            name='category',
            field=models.CharField(choices=[('USER', 'User'), ('STUDENT_RECORD', 'Student Record'), ('COURSE', 'Course'), ('ENROLLMENT', 'Enrollment'), ('GRADE', 'Grade'), ('MOODLE', 'Moodle'), ('NOTIFICATION', 'Notification'), ('ACADEMIC_CALENDAR', 'Academic Calendar'), ('LTI', 'LTI'), ('SYSTEM', 'System'), ('AI', 'AI')], db_index=True, max_length=32),
        ),
    ]
