# Generated by Django 5.2.7 on 2026-05-08 23:59

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('students', '0002_studentcorrectionrequest'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AtRiskAlert',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('severity', models.CharField(choices=[('HIGH', 'High'), ('MEDIUM', 'Medium'), ('LOW', 'Low')], max_length=8)),
                ('active_signals', models.JSONField(default=list)),
                ('explanation', models.TextField()),
                ('provider', models.CharField(default='deterministic', max_length=40)),
                ('model_name', models.CharField(blank=True, max_length=120)),
                ('is_acknowledged', models.BooleanField(default=False)),
                ('acknowledged_at', models.DateTimeField(blank=True, null=True)),
                ('is_closed', models.BooleanField(default=False)),
                ('closed_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('acknowledged_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='acknowledged_at_risk_alerts', to=settings.AUTH_USER_MODEL)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='at_risk_alerts', to='students.studentprofile')),
            ],
            options={
                'ordering': ['-severity', '-created_at'],
                'indexes': [models.Index(fields=['student', '-created_at'], name='atrisk_student_idx'), models.Index(fields=['severity', '-created_at'], name='atrisk_severity_idx'), models.Index(fields=['is_acknowledged', '-created_at'], name='atrisk_ack_idx')],
            },
        ),
    ]
