# Generated by Django 5.2.7 on 2026-05-01 13:00

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='KnowledgeIngestionRun',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('status', models.CharField(choices=[('STARTED', 'Started'), ('SUCCEEDED', 'Succeeded'), ('FAILED', 'Failed'), ('PARTIAL', 'Partial')], default='STARTED', max_length=16)),
                ('started_at', models.DateTimeField(auto_now_add=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('sources_processed', models.PositiveIntegerField(default=0)),
                ('chunks_created', models.PositiveIntegerField(default=0)),
                ('chunks_upserted', models.PositiveIntegerField(default=0)),
                ('failure_count', models.PositiveIntegerField(default=0)),
                ('last_error', models.TextField(blank=True)),
                ('metadata', models.JSONField(blank=True, default=dict)),
            ],
            options={
                'ordering': ['-started_at', 'id'],
            },
        ),
        migrations.CreateModel(
            name='KnowledgeSource',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('source_type', models.CharField(choices=[('ACADEMIC_CALENDAR', 'Academic Calendar'), ('COURSE_CATALOG', 'Course Catalog'), ('ACADEMIC_REGULATIONS', 'Academic Regulations'), ('REGISTRATION_PROCEDURES', 'Registration Procedures'), ('FEE_SCHEDULE', 'Fee Schedule'), ('SYSTEM_POLICY', 'System Policy'), ('OTHER', 'Other')], max_length=40)),
                ('title', models.CharField(max_length=180)),
                ('description', models.TextField(blank=True)),
                ('source_path', models.CharField(blank=True, max_length=500)),
                ('content', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('DRAFT', 'Draft'), ('READY', 'Ready'), ('INGESTED', 'Ingested'), ('FAILED', 'Failed')], default='DRAFT', max_length=16)),
                ('visibility', models.CharField(choices=[('PUBLIC_STUDENT', 'Public Student'), ('STAFF_ONLY', 'Staff Only'), ('ADMIN_ONLY', 'Admin Only')], default='PUBLIC_STUDENT', max_length=24)),
                ('checksum_sha256', models.CharField(blank=True, max_length=64)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_knowledge_sources', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['source_type', 'title'],
            },
        ),
        migrations.CreateModel(
            name='KnowledgeChunk',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('chunk_index', models.PositiveIntegerField()),
                ('text', models.TextField()),
                ('token_count', models.PositiveIntegerField(default=0)),
                ('vector_id', models.CharField(db_index=True, max_length=128)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('source', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chunks', to='knowledge.knowledgesource')),
            ],
            options={
                'ordering': ['source__title', 'chunk_index'],
            },
        ),
        migrations.AddConstraint(
            model_name='knowledgesource',
            constraint=models.UniqueConstraint(fields=('source_type', 'title'), name='knowledge_unique_source_type_title'),
        ),
        migrations.AddConstraint(
            model_name='knowledgechunk',
            constraint=models.UniqueConstraint(fields=('source', 'chunk_index'), name='knowledge_unique_chunk_per_source_index'),
        ),
    ]
