# Generated by Django 5.2.7 on 2026-04-26 18:35

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0002_seed_defaults'),
        ('integration', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='integrationoutboxevent',
            name='attempts',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='integrationoutboxevent',
            name='last_attempt_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='integrationoutboxevent',
            name='last_error',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='integrationoutboxevent',
            name='processed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name='MoodleCourseMap',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('moodle_course_id', models.PositiveIntegerField(unique=True)),
                ('moodle_shortname', models.CharField(max_length=255)),
                ('moodle_category_id', models.PositiveIntegerField()),
                ('grade_component', models.CharField(blank=True, max_length=64)),
                ('grade_activity_id', models.PositiveIntegerField(blank=True, null=True)),
                ('grade_item_number', models.PositiveIntegerField(blank=True, null=True)),
                ('grade_item_label', models.CharField(blank=True, max_length=255)),
                ('last_synced_at', models.DateTimeField(auto_now=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('section', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='moodle_course_map', to='academics.coursesection')),
            ],
            options={
                'ordering': ['section_id'],
            },
        ),
        migrations.CreateModel(
            name='MoodleUserMap',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('moodle_user_id', models.PositiveIntegerField(unique=True)),
                ('moodle_username', models.CharField(max_length=150)),
                ('last_synced_at', models.DateTimeField(auto_now=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='moodle_user_map', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['user_id'],
            },
        ),
    ]
