# Generated by Django 5.2.7 on 2026-04-29 23:05

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0002_seed_defaults'),
        ('integration', '0002_integrationoutboxevent_attempts_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='LtiOidcState',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('state', models.CharField(max_length=160, unique=True)),
                ('nonce', models.CharField(max_length=160, unique=True)),
                ('issuer', models.URLField(max_length=500)),
                ('client_id', models.CharField(max_length=255)),
                ('deployment_id', models.CharField(blank=True, max_length=255)),
                ('login_hint', models.CharField(max_length=500)),
                ('lti_message_hint', models.CharField(blank=True, max_length=500)),
                ('target_link_uri', models.URLField(max_length=1000)),
                ('expires_at', models.DateTimeField()),
                ('used_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['state', 'expires_at'], name='integration_state_dc306b_idx'), models.Index(fields=['nonce', 'expires_at'], name='integration_nonce_57342e_idx')],
            },
        ),
        migrations.CreateModel(
            name='LtiLaunchSession',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('session_token_hash', models.CharField(max_length=64, unique=True)),
                ('issuer', models.URLField(max_length=500)),
                ('client_id', models.CharField(max_length=255)),
                ('deployment_id', models.CharField(max_length=255)),
                ('tool_slug', models.CharField(max_length=64)),
                ('moodle_subject', models.CharField(max_length=255)),
                ('moodle_user_id', models.CharField(blank=True, max_length=64)),
                ('moodle_course_id', models.CharField(blank=True, max_length=64)),
                ('moodle_roles', models.JSONField(blank=True, default=list)),
                ('launch_claims', models.JSONField(blank=True, default=dict)),
                ('expires_at', models.DateTimeField()),
                ('last_accessed_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('section', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='lti_launch_sessions', to='academics.coursesection')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='lti_launch_sessions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['session_token_hash', 'expires_at'], name='integration_session_45a9ba_idx'), models.Index(fields=['tool_slug', 'expires_at'], name='integration_tool_sl_b95dde_idx'), models.Index(fields=['moodle_user_id'], name='integration_moodle__bfdb47_idx'), models.Index(fields=['moodle_course_id'], name='integration_moodle__75600d_idx')],
            },
        ),
    ]
