# Generated by Django 5.2.7 on 2026-05-11 21:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_user_full_name_user_must_reset_password_accesslog'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='secondary_roles',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
