# Generated by Django 5.2.7 on 2026-04-15 13:38

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('students', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AcademicStandingRule',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('standing', models.CharField(choices=[('GOOD_STANDING', 'Good Standing'), ('ACADEMIC_WARNING', 'Academic Warning'), ('PROBATION', 'Probation'), ('SUSPENDED', 'Suspended')], max_length=32)),
                ('minimum_gpa', models.DecimalField(decimal_places=2, max_digits=4)),
                ('maximum_gpa', models.DecimalField(blank=True, decimal_places=2, max_digits=4, null=True)),
                ('display_order', models.PositiveSmallIntegerField(default=0)),
            ],
            options={
                'ordering': ['display_order', '-minimum_gpa'],
            },
        ),
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('course_code', models.CharField(max_length=32, unique=True)),
                ('course_title', models.CharField(max_length=255)),
                ('department', models.CharField(max_length=128)),
                ('credit_hours', models.PositiveSmallIntegerField()),
                ('description', models.TextField(blank=True)),
                ('programme_code', models.CharField(blank=True, max_length=128)),
                ('max_capacity', models.PositiveIntegerField(default=50)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['course_code'],
            },
        ),
        migrations.CreateModel(
            name='GradingScaleBand',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('letter_grade', models.CharField(max_length=8)),
                ('minimum_score', models.DecimalField(decimal_places=2, max_digits=5)),
                ('maximum_score', models.DecimalField(decimal_places=2, max_digits=5)),
                ('grade_points', models.DecimalField(decimal_places=2, max_digits=4)),
                ('is_passing', models.BooleanField(default=True)),
                ('display_order', models.PositiveSmallIntegerField(default=0)),
            ],
            options={
                'ordering': ['display_order', '-minimum_score'],
            },
        ),
        migrations.CreateModel(
            name='CourseSection',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('section_code', models.CharField(max_length=32)),
                ('room', models.CharField(max_length=128)),
                ('semester', models.CharField(max_length=64)),
                ('academic_year', models.CharField(max_length=32)),
                ('max_capacity', models.PositiveIntegerField()),
                ('registration_opens_at', models.DateTimeField()),
                ('registration_closes_at', models.DateTimeField()),
                ('drop_deadline', models.DateTimeField()),
                ('attendance_threshold', models.DecimalField(decimal_places=2, default=75, max_digits=5)),
                ('status', models.CharField(choices=[('ACTIVE', 'Active'), ('ARCHIVED', 'Archived')], default='ACTIVE', max_length=16)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sections', to='academics.course')),
                ('faculty_user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='course_sections', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['course__course_code', 'section_code'],
            },
        ),
        migrations.CreateModel(
            name='AttendanceSession',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('session_date', models.DateField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('recorded_by_user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='recorded_attendance_sessions', to=settings.AUTH_USER_MODEL)),
                ('section', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attendance_sessions', to='academics.coursesection')),
            ],
        ),
        migrations.CreateModel(
            name='Enrollment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('enrollment_status', models.CharField(choices=[('ENROLLED', 'Enrolled'), ('DROPPED', 'Dropped'), ('WAITLISTED', 'Waitlisted'), ('TRANSFERRED', 'Transferred')], max_length=16)),
                ('actor_role', models.CharField(max_length=32)),
                ('is_active', models.BooleanField(default=True)),
                ('reason', models.TextField(blank=True)),
                ('enrolled_at', models.DateTimeField(auto_now_add=True)),
                ('dropped_at', models.DateTimeField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('actor_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='enrollment_actions', to=settings.AUTH_USER_MODEL)),
                ('section', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='enrollments', to='academics.coursesection')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='enrollments', to='students.studentprofile')),
            ],
            options={
                'ordering': ['-enrolled_at', '-updated_at'],
            },
        ),
        migrations.CreateModel(
            name='EnrollmentEvent',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('event_type', models.CharField(choices=[('ENROLL', 'Enroll'), ('DROP', 'Drop'), ('TRANSFER', 'Transfer'), ('WAITLIST', 'Waitlist')], max_length=16)),
                ('actor_role', models.CharField(max_length=32)),
                ('details', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('actor_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='enrollment_event_actions', to=settings.AUTH_USER_MODEL)),
                ('enrollment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='events', to='academics.enrollment')),
            ],
            options={
                'ordering': ['created_at', 'id'],
            },
        ),
        migrations.CreateModel(
            name='GradeRecord',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('numeric_score', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('letter_grade', models.CharField(blank=True, max_length=8)),
                ('grade_points', models.DecimalField(decimal_places=2, default=0, max_digits=4)),
                ('grade_status', models.CharField(choices=[('DRAFT', 'Draft'), ('OFFICIAL', 'Official')], default='DRAFT', max_length=16)),
                ('special_code', models.CharField(blank=True, choices=[('I', 'Incomplete'), ('W', 'Withdrawn')], max_length=8)),
                ('entered_at', models.DateTimeField(auto_now_add=True)),
                ('officialised_at', models.DateTimeField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('entered_by_user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='entered_grade_records', to=settings.AUTH_USER_MODEL)),
                ('officialised_by_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='officialised_grade_records', to=settings.AUTH_USER_MODEL)),
                ('section', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='grade_records', to='academics.coursesection')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='grade_records', to='students.studentprofile')),
            ],
        ),
        migrations.CreateModel(
            name='GradeChangeLog',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('previous_numeric_score', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('new_numeric_score', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('previous_letter_grade', models.CharField(blank=True, max_length=8)),
                ('new_letter_grade', models.CharField(blank=True, max_length=8)),
                ('previous_grade_status', models.CharField(choices=[('DRAFT', 'Draft'), ('OFFICIAL', 'Official')], max_length=16)),
                ('new_grade_status', models.CharField(choices=[('DRAFT', 'Draft'), ('OFFICIAL', 'Official')], max_length=16)),
                ('reason', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('actor_user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='grade_change_logs', to=settings.AUTH_USER_MODEL)),
                ('grade_record', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='change_logs', to='academics.graderecord')),
            ],
            options={
                'ordering': ['-created_at', '-id'],
            },
        ),
        migrations.CreateModel(
            name='SectionTimetable',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('day_of_week', models.CharField(max_length=16)),
                ('start_time', models.TimeField()),
                ('end_time', models.TimeField()),
                ('section', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='timetables', to='academics.coursesection')),
            ],
            options={
                'ordering': ['day_of_week', 'start_time', 'id'],
            },
        ),
        migrations.CreateModel(
            name='WaitlistEntry',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('PROMOTED', 'Promoted'), ('CANCELLED', 'Cancelled')], default='PENDING', max_length=16)),
                ('joined_at', models.DateTimeField(auto_now_add=True)),
                ('promoted_at', models.DateTimeField(blank=True, null=True)),
                ('promoted_by_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='promoted_waitlist_entries', to=settings.AUTH_USER_MODEL)),
                ('section', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='waitlist_entries', to='academics.coursesection')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='waitlist_entries', to='students.studentprofile')),
            ],
            options={
                'ordering': ['joined_at', 'id'],
            },
        ),
        migrations.CreateModel(
            name='AttendanceRecord',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('status', models.CharField(choices=[('PRESENT', 'Present'), ('ABSENT', 'Absent'), ('EXCUSED', 'Excused')], max_length=16)),
                ('recorded_at', models.DateTimeField(auto_now=True)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attendance_records', to='students.studentprofile')),
                ('attendance_session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='records', to='academics.attendancesession')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('attendance_session', 'student'), name='academics_unique_attendance_record')],
            },
        ),
        migrations.CreateModel(
            name='CoursePrerequisite',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='prerequisites', to='academics.course')),
                ('prerequisite_course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='required_for_courses', to='academics.course')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('course', 'prerequisite_course'), name='academics_unique_prerequisite_pair')],
            },
        ),
        migrations.AddConstraint(
            model_name='coursesection',
            constraint=models.UniqueConstraint(fields=('course', 'section_code', 'semester', 'academic_year'), name='academics_unique_section_per_term'),
        ),
        migrations.AddConstraint(
            model_name='graderecord',
            constraint=models.UniqueConstraint(fields=('student', 'section'), name='academics_unique_grade_per_student_section'),
        ),
    ]
