# Generated by Django 5.2.7 on 2026-05-11 19:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0002_seed_defaults'),
        ('structure', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='department_ref',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='courses', to='structure.department'),
        ),
        migrations.AddField(
            model_name='course',
            name='programme_ref',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='courses', to='structure.programme'),
        ),
        migrations.AddField(
            model_name='coursesection',
            name='stream',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sections', to='structure.stream'),
        ),
    ]
