# Generated by Django 5.2.7 on 2026-05-11 21:08

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0003_course_department_ref_course_programme_ref_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='enrollment',
            name='approval_required',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='enrollment',
            name='approved_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='enrollment',
            name='approved_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_enrollments', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='enrollment',
            name='rejection_reason',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='enrollment',
            name='enrollment_status',
            field=models.CharField(choices=[('ENROLLED', 'Enrolled'), ('DROPPED', 'Dropped'), ('WAITLISTED', 'Waitlisted'), ('TRANSFERRED', 'Transferred'), ('PENDING_APPROVAL', 'Pending Approval')], max_length=16),
        ),
        migrations.AlterField(
            model_name='enrollmentevent',
            name='event_type',
            field=models.CharField(choices=[('ENROLL', 'Enroll'), ('DROP', 'Drop'), ('TRANSFER', 'Transfer'), ('WAITLIST', 'Waitlist'), ('PENDING_APPROVAL', 'Pending Approval'), ('APPROVED', 'Approved'), ('REJECTED', 'Rejected')], max_length=16),
        ),
    ]
