# Generated by Django 5.2.7 on 2026-05-11 21:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0004_add_pending_approval_enrollment_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='graderecord',
            name='ca_score',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True),
        ),
        migrations.AddField(
            model_name='graderecord',
            name='exam_score',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True),
        ),
    ]
