# Generated by Django 5.2.7 on 2026-05-01 00:21

import apps.documents.models
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('students', '0002_studentcorrectionrequest'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='StudentDocument',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('document_type', models.CharField(choices=[('NRC_ID', 'NRC/ID'), ('ADMISSION_LETTER', 'Admission Letter'), ('TRANSCRIPT', 'Transcript'), ('APPEAL_LETTER', 'Appeal Letter'), ('CLEARANCE_FORM', 'Clearance Form'), ('MEDICAL_SUPPORT', 'Medical/Wellbeing Supporting Document'), ('OTHER', 'Other Supporting Document')], max_length=32)),
                ('title', models.CharField(max_length=160)),
                ('description', models.TextField(blank=True)),
                ('file', models.FileField(upload_to=apps.documents.models.student_document_upload_path)),
                ('original_filename', models.CharField(max_length=255)),
                ('content_type', models.CharField(max_length=160)),
                ('file_size', models.PositiveIntegerField()),
                ('checksum_sha256', models.CharField(blank=True, max_length=64)),
                ('visibility', models.CharField(choices=[('ADMIN_ONLY', 'Admin Only'), ('ADMIN_ADVISOR', 'Admin and Advisor'), ('STUDENT_VISIBLE', 'Student Visible')], default='ADMIN_ONLY', max_length=24)),
                ('status', models.CharField(choices=[('PENDING_REVIEW', 'Pending Review'), ('APPROVED', 'Approved'), ('REJECTED', 'Rejected'), ('ARCHIVED', 'Archived')], default='PENDING_REVIEW', max_length=24)),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('review_note', models.TextField(blank=True)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_student_documents', to=settings.AUTH_USER_MODEL)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='students.studentprofile')),
                ('uploaded_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='uploaded_student_documents', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at', '-updated_at', 'title'],
                'indexes': [models.Index(fields=['student', 'status', '-created_at'], name='doc_student_status_idx'), models.Index(fields=['document_type', 'status'], name='doc_type_status_idx'), models.Index(fields=['visibility', 'status'], name='doc_visibility_status_idx'), models.Index(fields=['uploaded_by', '-created_at'], name='doc_uploaded_by_idx')],
            },
        ),
    ]
