# Generated by Django 5.2.7 on 2026-05-01 21:46

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('students', '0002_studentcorrectionrequest'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CopilotSession',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=120)),
                ('status', models.CharField(choices=[('ACTIVE', 'Active'), ('ARCHIVED', 'Archived')], default='ACTIVE', max_length=16)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('last_message_at', models.DateTimeField(blank=True, null=True)),
                ('student', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='copilot_sessions', to='students.studentprofile')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='copilot_sessions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-last_message_at', '-created_at', '-id'],
            },
        ),
        migrations.CreateModel(
            name='CopilotMessage',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('role', models.CharField(choices=[('USER', 'User'), ('ASSISTANT', 'Assistant'), ('SYSTEM', 'System')], max_length=16)),
                ('content', models.TextField()),
                ('safe_content', models.TextField(blank=True)),
                ('source_references', models.JSONField(blank=True, default=list)),
                ('confidence', models.CharField(choices=[('HIGH', 'High'), ('MEDIUM', 'Medium'), ('LOW', 'Low'), ('UNSUPPORTED', 'Unsupported')], default='UNSUPPORTED', max_length=16)),
                ('provider', models.CharField(choices=[('deterministic', 'Deterministic'), ('openai_compatible', 'OpenAI compatible'), ('system', 'System')], default='system', max_length=40)),
                ('model_name', models.CharField(blank=True, max_length=120)),
                ('retrieval_query', models.TextField(blank=True)),
                ('retrieved_chunk_count', models.PositiveIntegerField(default=0)),
                ('latency_ms', models.PositiveIntegerField(blank=True, null=True)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='copilot.copilotsession')),
            ],
            options={
                'ordering': ['created_at', 'id'],
            },
        ),
        migrations.CreateModel(
            name='AIAuditLog',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('action', models.CharField(choices=[('COPILOT_QUERY', 'Co-pilot query'), ('COPILOT_RESPONSE', 'Co-pilot response'), ('COPILOT_LOW_CONFIDENCE', 'Co-pilot low confidence'), ('COPILOT_PROVIDER_ERROR', 'Co-pilot provider error'), ('COPILOT_RETRIEVAL_ONLY', 'Co-pilot retrieval only')], db_index=True, max_length=40)),
                ('input_text', models.TextField(blank=True)),
                ('output_text', models.TextField(blank=True)),
                ('source_count', models.PositiveIntegerField(default=0)),
                ('confidence', models.CharField(choices=[('HIGH', 'High'), ('MEDIUM', 'Medium'), ('LOW', 'Low'), ('UNSUPPORTED', 'Unsupported')], default='UNSUPPORTED', max_length=16)),
                ('provider', models.CharField(choices=[('deterministic', 'Deterministic'), ('openai_compatible', 'OpenAI compatible'), ('system', 'System')], default='system', max_length=40)),
                ('model_name', models.CharField(blank=True, max_length=120)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_ai_audit_logs', to=settings.AUTH_USER_MODEL)),
                ('student', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ai_audit_logs', to='students.studentprofile')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ai_audit_logs', to=settings.AUTH_USER_MODEL)),
                ('message', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ai_audit_logs', to='copilot.copilotmessage')),
                ('session', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ai_audit_logs', to='copilot.copilotsession')),
            ],
            options={
                'ordering': ['-created_at', '-id'],
            },
        ),
        migrations.CreateModel(
            name='CopilotFeedback',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('rating', models.CharField(choices=[('HELPFUL', 'Helpful'), ('NOT_HELPFUL', 'Not helpful')], max_length=16)),
                ('comment', models.TextField(blank=True)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='copilot_feedback', to=settings.AUTH_USER_MODEL)),
                ('message', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='feedback', to='copilot.copilotmessage')),
            ],
            options={
                'ordering': ['-created_at', '-id'],
                'constraints': [models.UniqueConstraint(fields=('message', 'user'), name='copilot_unique_feedback_per_message_user')],
            },
        ),
        migrations.AddIndex(
            model_name='copilotsession',
            index=models.Index(fields=['user', 'status', '-last_message_at'], name='copilot_session_user_idx'),
        ),
        migrations.AddIndex(
            model_name='copilotsession',
            index=models.Index(fields=['student', 'status'], name='copilot_session_student_idx'),
        ),
        migrations.AddIndex(
            model_name='copilotmessage',
            index=models.Index(fields=['session', 'created_at'], name='copilot_msg_session_idx'),
        ),
        migrations.AddIndex(
            model_name='copilotmessage',
            index=models.Index(fields=['role', 'created_at'], name='copilot_msg_role_idx'),
        ),
        migrations.AddIndex(
            model_name='aiauditlog',
            index=models.Index(fields=['action', 'created_at'], name='ai_audit_action_idx'),
        ),
        migrations.AddIndex(
            model_name='aiauditlog',
            index=models.Index(fields=['user', 'created_at'], name='ai_audit_user_idx'),
        ),
        migrations.AddIndex(
            model_name='aiauditlog',
            index=models.Index(fields=['student', 'created_at'], name='ai_audit_student_idx'),
        ),
        migrations.AddIndex(
            model_name='aiauditlog',
            index=models.Index(fields=['session', 'created_at'], name='ai_audit_session_idx'),
        ),
    ]
