# Generated by Django 5.2.7 on 2026-05-08 23:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('copilot', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aiauditlog',
            name='action',
            field=models.CharField(choices=[('COPILOT_QUERY', 'Co-pilot query'), ('COPILOT_RESPONSE', 'Co-pilot response'), ('COPILOT_LOW_CONFIDENCE', 'Co-pilot low confidence'), ('COPILOT_PROVIDER_ERROR', 'Co-pilot provider error'), ('COPILOT_RETRIEVAL_ONLY', 'Co-pilot retrieval only'), ('SUMMARISATION_REQUEST', 'Summarisation request'), ('SUMMARISATION_APPROVED', 'Summarisation approved')], db_index=True, max_length=40),
        ),
    ]
