# Generated by Django 6.0.5 on 2026-05-10 15:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("copilot", "0003_alter_aiauditlog_action"),
    ]

    operations = [
        migrations.AlterField(
            model_name="aiauditlog",
            name="provider",
            field=models.CharField(
                choices=[
                    ("deterministic", "Deterministic"),
                    ("openai_compatible", "OpenAI compatible"),
                    ("gemini", "Google Gemini"),
                    ("system", "System"),
                ],
                default="system",
                max_length=40,
            ),
        ),
        migrations.AlterField(
            model_name="copilotmessage",
            name="provider",
            field=models.CharField(
                choices=[
                    ("deterministic", "Deterministic"),
                    ("openai_compatible", "OpenAI compatible"),
                    ("gemini", "Google Gemini"),
                    ("system", "System"),
                ],
                default="system",
                max_length=40,
            ),
        ),
    ]
