# Generated by Django 5.2.7 on 2026-04-15 13:38

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='StudentProfile',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('student_number', models.CharField(max_length=32, unique=True)),
                ('national_id', models.CharField(blank=True, max_length=64)),
                ('date_of_birth', models.DateField()),
                ('gender', models.CharField(max_length=32)),
                ('programme', models.CharField(max_length=128)),
                ('year_of_study', models.PositiveSmallIntegerField()),
                ('academic_standing', models.CharField(choices=[('GOOD_STANDING', 'Good Standing'), ('ACADEMIC_WARNING', 'Academic Warning'), ('PROBATION', 'Probation'), ('SUSPENDED', 'Suspended')], default='GOOD_STANDING', max_length=32)),
                ('cumulative_gpa', models.DecimalField(decimal_places=2, default=0, max_digits=4)),
                ('standing_override_reason', models.CharField(blank=True, max_length=255)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='student_profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['student_number'],
            },
        ),
        migrations.CreateModel(
            name='FinancialFlag',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('flag_type', models.CharField(max_length=64)),
                ('reason', models.TextField()),
                ('effective_date', models.DateField()),
                ('cleared_date', models.DateField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by_user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='created_financial_flags', to=settings.AUTH_USER_MODEL)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='financial_flags', to='students.studentprofile')),
            ],
            options={
                'ordering': ['-effective_date', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='AdvisorAssignment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('effective_from', models.DateField()),
                ('effective_to', models.DateField(blank=True, null=True)),
                ('is_current', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('advisor_user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='assigned_advisee_records', to=settings.AUTH_USER_MODEL)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='advisor_assignments', to='students.studentprofile')),
            ],
            options={
                'ordering': ['-effective_from', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='AdvisingNote',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('note_text', models.TextField()),
                ('status', models.CharField(choices=[('DRAFT', 'Draft'), ('APPROVED', 'Approved')], default='DRAFT', max_length=16)),
                ('approved_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('approved_by_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='approved_advising_notes', to=settings.AUTH_USER_MODEL)),
                ('created_by_user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='created_advising_notes', to=settings.AUTH_USER_MODEL)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='advising_notes', to='students.studentprofile')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
