# Generated by Django 5.2.7 on 2026-05-11 19:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('structure', '0001_initial'),
        ('students', '0002_studentcorrectionrequest'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentprofile',
            name='programme_ref',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='students', to='structure.programme'),
        ),
    ]
