# Generated by Django 5.2.7 on 2026-05-08 21:54

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('students', '0002_studentcorrectionrequest'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SummarisationRequest',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('raw_input_text', models.TextField()),
                ('ai_output', models.JSONField(default=dict)),
                ('human_edited_output', models.JSONField(blank=True, null=True)),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('APPROVED', 'Approved'), ('DISCARDED', 'Discarded')], default='PENDING', max_length=16)),
                ('provider', models.CharField(max_length=40)),
                ('model_name', models.CharField(blank=True, max_length=120)),
                ('latency_ms', models.PositiveIntegerField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('approved_at', models.DateTimeField(blank=True, null=True)),
                ('advising_note', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='summarisation_requests', to='students.advisingnote')),
                ('student', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='summarisation_requests', to='students.studentprofile')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='summarisation_requests', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['user', '-created_at'], name='summ_user_idx'), models.Index(fields=['student', '-created_at'], name='summ_student_idx'), models.Index(fields=['status', '-created_at'], name='summ_status_idx')],
            },
        ),
    ]
